services:
  backend:
    build: ./example-backend/
    volumes:
      - ./example-backend/:/devopswithdocker
    container_name: backend
    ports:
      - 8080:8080

  frontend:
    build: ./example-frontend/
    volumes:
      - ./example-frontend/:/devopswithdocker
    container_name: frontend
    ports:
      - 5001:5001
